# Generated by Django 5.2.17 on 2026-09-13 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('text', models.TextField(blank=True)),
                ('depth', models.PositiveSmallIntegerField(default=1)),
                ('edition_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_amended', models.BooleanField(default=False, help_text='True where Particular Conditions amend the standard form.')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('amended_by_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='clauses.clause')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='projects.project')),
                ('source_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='documents.documentsection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clauses_clause',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ContractualObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_number', models.CharField(db_index=True, max_length=32)),
                ('edition_code', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(choices=[('notice', 'Give notice'), ('submit', 'Submit'), ('pay', 'Pay'), ('determine', 'Determine'), ('instruct', 'Instruct'), ('perform', 'Perform'), ('certify', 'Certify'), ('respond', 'Respond'), ('other', 'Other')], db_index=True, max_length=32)),
                ('summary', models.CharField(max_length=512)),
                ('obligated_party_role', models.CharField(blank=True, help_text="Role as written in the contract, e.g. 'contractor', 'engineer'.", max_length=32)),
                ('counterparty_role', models.CharField(blank=True, max_length=32)),
                ('required_action', models.TextField(blank=True)),
                ('required_content', models.TextField(blank=True, help_text='What the communication or submission must contain.')),
                ('required_method', models.CharField(blank=True, help_text="e.g. 'in writing', 'Notice'.", max_length=128)),
                ('period_days', models.IntegerField(blank=True, null=True)),
                ('period_is_working_days', models.BooleanField(default=False)),
                ('trigger_description', models.TextField(blank=True, help_text="What starts the period running, in the contract's words.")),
                ('is_condition_precedent', models.BooleanField(default=False, help_text='Whether compliance is a condition of entitlement. Drives severity, not the arithmetic — and differs between editions for the same obligation.')),
                ('consequence_of_breach', models.TextField(blank=True)),
                ('is_ai_extracted', models.BooleanField(default=False)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='clauses.clause')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obligated_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='projects.party')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clauses_contractual_obligation',
                'ordering': ['clause_number'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('clause_number', models.CharField(blank=True, max_length=32)),
                ('trigger_date', models.DateField(blank=True, help_text='When the period started. Null means not established.', null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('satisfied_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due_soon', 'Due soon'), ('overdue', 'Overdue'), ('met', 'Met'), ('missed', 'Missed'), ('not_applicable', 'Not applicable'), ('indeterminate', 'Indeterminate')], db_index=True, default='indeterminate', max_length=16)),
                ('is_condition_precedent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='clauses.contractualobligation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='projects.project')),
            ],
            options={
                'db_table': 'clauses_deadline',
                'ordering': ['due_date'],
            },
        ),
    ]
