# Generated by Django 5.2.17 on 2026-09-13 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clauses', '0001_initial'),
        ('correspondence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='satisfied_by_correspondence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfied_deadlines', to='correspondence.correspondence'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['project', 'number'], name='clauses_cla_project_a3f667_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['project', 'is_amended'], name='clauses_cla_project_94e015_idx'),
        ),
        migrations.AddConstraint(
            model_name='clause',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='uniq_clause_per_project'),
        ),
        migrations.AddIndex(
            model_name='contractualobligation',
            index=models.Index(fields=['project', 'category'], name='clauses_con_project_fd35ea_idx'),
        ),
        migrations.AddIndex(
            model_name='contractualobligation',
            index=models.Index(fields=['project', 'clause_number'], name='clauses_con_project_7482f1_idx'),
        ),
        migrations.AddIndex(
            model_name='contractualobligation',
            index=models.Index(fields=['project', 'is_condition_precedent'], name='clauses_con_project_984581_idx'),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['project', 'status'], name='clauses_dea_project_3762bc_idx'),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['project', 'due_date'], name='clauses_dea_project_d4c07e_idx'),
        ),
    ]
