export * as adminApi from './admin'
export * as aiApi from './ai'
export * as authApi from './auth'
export * as claimsApi from './claims'
export * as correspondenceApi from './correspondence'
export * as dashboardApi from './dashboard'
export * as documentsApi from './documents'
export * as healthApi from './health'
export * as knowledgeApi from './knowledge'
export * as notificationsApi from './notifications'
export * as projectsApi from './projects'
export * as reportsApi from './reports'
export * as searchApi from './search'
export { ApiError, API_BASE_URL, http } from './client'
