# Generated by Django 5.2.17 on 2026-09-12 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ingest', 'Document ingestion'), ('reprocess', 'Reprocess document'), ('reembed', 'Regenerate embeddings')], default='ingest', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('current_stage', models.CharField(blank=True, db_index=True, max_length=32)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('state', models.JSONField(blank=True, default=dict, help_text='Serialised PipelineState. The authoritative record of progress.')),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_message', models.TextField(blank=True, help_text='Operator-facing failure reason. Surfaced in the UI as a job failure; never returned as an answer or fed to a model.')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False, help_text='Cooperative cancellation. A running stage checks this between units of work; there is no way to interrupt a stage mid-page, and killing the worker would leave the state machine inconsistent.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.documentversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingestion_processing_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(db_index=True, max_length=32)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(max_length=16)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ingestion.processingjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingestion_stage_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'created_at'], name='ingestion_p_status_ef27d9_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['document_version', '-created_at'], name='ingestion_p_documen_934ca0_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('document_version',), name='uniq_active_job_per_version'),
        ),
        migrations.AddIndex(
            model_name='stagelog',
            index=models.Index(fields=['job', 'created_at'], name='ingestion_s_job_id_d88303_idx'),
        ),
    ]
