# Generated by Django 5.2.17 on 2026-09-15 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('include_knowledge_base', models.BooleanField(default=True)),
                ('edition_code', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('failed', 'Failed')], max_length=16)),
                ('response', models.JSONField(blank=True, default=dict, help_text='The answer exactly as returned: summary, findings, citations, sources.')),
                ('model', models.CharField(blank=True, max_length=128)),
                ('prompt_identifier', models.CharField(blank=True, max_length=128)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_question',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='ai_question_project_82df4c_idx')],
            },
        ),
    ]
