# Generated by Django 5.2.17 on 2026-10-02 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBenchmarkRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('current_step', models.CharField(blank=True, max_length=160)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('include_pulls', models.BooleanField(default=False, help_text='Download recommended models that are missing. Requires a route to the model library, which an air-gapped installation does not have.')),
                ('pull_targets', models.JSONField(blank=True, default=list, help_text='Models the operator asked to download.')),
                ('runtime_version', models.CharField(blank=True, max_length=64)),
                ('host_capacity', models.JSONField(blank=True, default=dict)),
                ('detected_profile', models.CharField(blank=True, max_length=16)),
                ('profile_basis', models.CharField(blank=True, max_length=16)),
                ('profile_explanation', models.TextField(blank=True)),
                ('probes', models.JSONField(blank=True, default=list, help_text='Per-model measurements, including the models that failed.')),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False, help_text='Cooperative cancellation, checked between models. A generation already in flight cannot be interrupted, and a download in progress is left to finish rather than abandoned part-written.')),
                ('scope_marker', models.CharField(default='installation', editable=False, max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_benchmark_runs', to='accounts.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model_benchmark_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(default='installation', editable=False, help_text='Singleton marker. One configuration per installation.', max_length=32, unique=True)),
                ('llm_model', models.CharField(blank=True, help_text='Answering and claim analysis. Blank falls back to DEFAULT_LLM_MODEL.', max_length=128)),
                ('drafting_llm_model', models.CharField(blank=True, help_text='Drafting a claim from a document. Blank falls back to the answering model, which is the previous behaviour.', max_length=128)),
                ('embedding_model', models.CharField(blank=True, max_length=128)),
                ('reranker_model', models.CharField(blank=True, max_length=128)),
                ('hardware_profile', models.CharField(blank=True, help_text='Measured profile, which the model registry uses to decide what to recommend. Blank falls back to HARDWARE_PROFILE.', max_length=16)),
                ('embedding_dimensions', models.PositiveIntegerField(blank=True, help_text='Vector width the selected embedding model was measured to produce. Stored as a cross-check: it must equal the stored column width, and a mismatch means retrieval is comparing vectors that are not comparable.', null=True)),
                ('source', models.CharField(choices=[('manual', 'Chosen by an administrator'), ('detected', 'Applied from a detection run')], default='manual', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('applied_by_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organization')),
                ('applied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_configurations', to='ai.modelbenchmarkrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model_configuration',
            },
        ),
        migrations.AddIndex(
            model_name='modelbenchmarkrun',
            index=models.Index(fields=['organization', '-created_at'], name='ai_model_be_organiz_6ab247_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelbenchmarkrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('scope_marker',), name='one_active_model_benchmark'),
        ),
    ]
