# Generated by Django 5.2.17 on 2026-09-15 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('claims', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('claim_assessment', 'Claim assessment'), ('claims_register', 'Claims register')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(help_text='The data the report was composed from, as it was.')),
                ('document', models.JSONField(help_text='The composed report: sections and blocks.')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('docx_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='reports_rep_project_636f22_idx'), models.Index(fields=['claim', 'report_type'], name='reports_rep_claim_i_e21153_idx')],
            },
        ),
    ]
