# Generated by Django 5.2.17 on 2026-09-15 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('document_processed', 'Document processed'), ('document_failed', 'Document processing failed'), ('knowledge_base_ready', 'Knowledge base ready to publish'), ('knowledge_base_quarantined', 'Knowledge base blocked by validation'), ('knowledge_base_failed', 'Knowledge base build failed'), ('knowledge_base_published', 'Knowledge base published'), ('analysis_completed', 'Claim analysis completed'), ('analysis_failed', 'Claim analysis failed'), ('deadline_approaching', 'Notice deadline approaching'), ('deadline_passed', 'Notice deadline passed')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Action required')], default='info', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.JSONField(blank=True, default=dict, help_text='Where the UI should take the reader: {name, params, query}.')),
                ('dedupe_key', models.CharField(help_text='Identifies the event. A redelivered task or a repeated deadline scan must not notify the same person about the same event twice.', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='uniq_notification_event')],
            },
        ),
    ]
