# Generated by Django 5.2.17 on 2026-09-13 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('claim_type', models.CharField(choices=[('eot', 'Extension of Time'), ('variation', 'Variation'), ('cost', 'Additional Cost'), ('delay', 'Delay'), ('disruption', 'Disruption'), ('acceleration', 'Acceleration'), ('payment', 'Payment'), ('compensation_event', 'Compensation Event'), ('other', 'Other')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('notified', 'Notified'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('determined', 'Determined'), ('agreed', 'Agreed'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=32)),
                ('event_date', models.DateField(blank=True, db_index=True, help_text='When the event occurred.', null=True)),
                ('awareness_date', models.DateField(blank=True, help_text='When the claiming Party became aware, or should have become aware. Frequently disputed, and the date notice periods run from. Null means not established — never assume one.', null=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('determination_date', models.DateField(blank=True, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_assessed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('time_claimed_days', models.IntegerField(blank=True, null=True)),
                ('time_awarded_days', models.IntegerField(blank=True, null=True)),
                ('contractual_basis', models.JSONField(blank=True, default=list, help_text="Clause numbers relied on, e.g. ['20.2.1', '8.5'].")),
                ('human_outcome', models.CharField(choices=[('substantiated', 'Substantiated'), ('partially_substantiated', 'Partially substantiated'), ('unsubstantiated', 'Unsubstantiated'), ('insufficient_evidence', 'Insufficient evidence'), ('not_assessed', 'Not assessed')], default='not_assessed', max_length=32)),
                ('human_assessment', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_assessed', to=settings.AUTH_USER_MODEL)),
                ('claimant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_made', to='projects.party')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='projects.project')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_received', to='projects.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_claim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('claim_submission', 'Claim submission'), ('notice', 'Notice'), ('supporting', 'Supporting'), ('response', 'Response'), ('determination', 'Determination')], default='supporting', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_links', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_claim_document',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='source_documents',
            field=models.ManyToManyField(blank=True, related_name='claims', through='claims.ClaimDocument', to='documents.document'),
        ),
        migrations.CreateModel(
            name='ClaimEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('triggering_event', 'Triggering event'), ('notice_given', 'Notice given'), ('notice_acknowledged', 'Notice acknowledged'), ('instruction', 'Instruction'), ('submission', 'Submission'), ('response', 'Response'), ('determination', 'Determination'), ('meeting', 'Meeting'), ('site_event', 'Site event'), ('programme_update', 'Programme update'), ('payment', 'Payment'), ('other', 'Other')], db_index=True, max_length=32)),
                ('occurred_on', models.DateField(db_index=True)),
                ('occurred_at_precision', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='day', help_text="How precisely the date is known. A source saying 'in March' is not the same as one saying '14 March', and a chronology that renders both identically overstates what the record establishes.", max_length=8)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('clause_references', models.JSONField(blank=True, default=list)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('is_ai_extracted', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, help_text='AI extraction confidence, when applicable.', null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='A human has confirmed this event. Unconfirmed AI events are shown distinctly rather than presented as established.')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='claims.claim')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.party')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_claim_event',
                'ordering': ['occurred_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('entitlement', 'Contractual entitlement'), ('notice_compliance', 'Notice compliance'), ('causation', 'Causation'), ('responsibility', 'Responsibility'), ('time_impact', 'Time impact'), ('quantum', 'Quantum'), ('mitigation', 'Mitigation'), ('other', 'Other')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('human_outcome', models.CharField(choices=[('substantiated', 'Substantiated'), ('partially_substantiated', 'Partially substantiated'), ('unsubstantiated', 'Unsubstantiated'), ('insufficient_evidence', 'Insufficient evidence'), ('not_assessed', 'Not assessed')], default='not_assessed', max_length=32)),
                ('human_assessment', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_claim_issue',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('stated_on', models.DateField(blank=True, null=True)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='claims.claimissue')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='projects.party')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_claim_position',
                'ordering': ['stated_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('relevance', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('neutral', 'Neutral'), ('unassessed', 'Unassessed')], db_index=True, default='unassessed', max_length=16)),
                ('weight', models.CharField(blank=True, choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], max_length=16)),
                ('is_ai_suggested', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='documents.document')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='claims.claimissue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='claimdocument',
            constraint=models.UniqueConstraint(fields=('claim', 'document', 'role'), name='uniq_claim_document_role'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['project', 'status'], name='claims_clai_project_8ea004_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['project', 'claim_type'], name='claims_clai_project_13bffc_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['project', '-event_date'], name='claims_clai_project_df4385_idx'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('reference', ''), _negated=True)), fields=('project', 'reference'), name='uniq_claim_reference_per_project'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('amount_claimed__isnull', True), ('amount_claimed__gte', 0), _connector='OR'), name='claim_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='claimevent',
            index=models.Index(fields=['project', 'occurred_on'], name='claims_clai_project_4119a7_idx'),
        ),
        migrations.AddIndex(
            model_name='claimevent',
            index=models.Index(fields=['claim', 'occurred_on'], name='claims_clai_claim_i_62a087_idx'),
        ),
        migrations.AddIndex(
            model_name='claimevent',
            index=models.Index(fields=['project', 'event_type'], name='claims_clai_project_54c55b_idx'),
        ),
        migrations.AddIndex(
            model_name='claimissue',
            index=models.Index(fields=['claim', 'category'], name='claims_clai_claim_i_eb889f_idx'),
        ),
        migrations.AddIndex(
            model_name='claimposition',
            index=models.Index(fields=['claim', 'issue'], name='claims_clai_claim_i_1c0dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['claim', 'relevance'], name='claims_evid_claim_i_8365fb_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['project', 'relevance'], name='claims_evid_project_8f8894_idx'),
        ),
    ]
