# Generated by Django 5.2.17 on 2026-09-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimissue',
            name='category',
            field=models.CharField(choices=[('entitlement', 'Contractual entitlement'), ('event', 'The triggering event'), ('notice_compliance', 'Notice compliance'), ('causation', 'Causation'), ('responsibility', 'Responsibility'), ('instruction', 'The instruction'), ('time_impact', 'Time impact'), ('cost_impact', 'Cost incurred'), ('quantum', 'Quantum'), ('mitigation', 'Mitigation'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
