# Generated by Django 5.2.17 on 2026-10-07 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claimissue_category'),
        ('documents', '0002_document_organization_alter_document_project_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_number', models.CharField(max_length=32)),
                ('obligation', models.CharField(choices=[('notice_of_claim', 'Notice of claim'), ('detailed_claim', 'Detailed claim / particulars')], default='notice_of_claim', max_length=32)),
                ('action', models.CharField(choices=[('amend', 'Amends the standard requirement'), ('add', 'Adds a requirement'), ('remove', 'Deletes the standard requirement')], default='amend', max_length=16)),
                ('status', models.CharField(choices=[('suggested', 'Suggested — not applied'), ('confirmed', 'Confirmed — applied'), ('rejected', 'Rejected')], db_index=True, default='suggested', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('day_count', models.CharField(blank=True, choices=[('calendar', 'Calendar days'), ('working', 'Working days')], max_length=16)),
                ('runs_from', models.CharField(blank=True, choices=[('awareness', 'The event / awareness of it'), ('notice', 'A notice under another provision')], max_length=16)),
                ('runs_from_clause', models.CharField(blank=True, max_length=32)),
                ('applies_to', models.CharField(blank=True, choices=[('all', 'All claims'), ('time', 'Claims for time'), ('money', 'Claims for money')], max_length=16)),
                ('is_condition_precedent', models.BooleanField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=128)),
                ('late_consequence', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_excerpt', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_deadlines', to='projects.project')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_contract_deadline',
                'ordering': ['clause_number', 'obligation', 'created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='claims_cont_project_c53d3a_idx')],
            },
        ),
    ]
