# Generated by Django 5.2.17 on 2026-09-12 22:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_collection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('document_type', models.CharField(db_index=True, help_text='Taxonomy code from claimiq.documents.domain.taxonomy.', max_length=64)),
                ('reference', models.CharField(blank=True, help_text='Project document reference or number.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, db_index=True, help_text='Date on the document itself, not the upload date.', null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcollection')),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=128)),
                ('file_size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(db_index=True, help_text='Content hash. Detects re-uploads of identical files.', max_length=64)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extraction_method', models.CharField(choices=[('digital', 'Digital text extraction'), ('ocr', 'OCR'), ('hybrid', 'Hybrid (digital + OCR)'), ('none', 'No text extracted')], default='none', max_length=16)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('quarantined', 'Quarantined'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('processing_error', models.TextField(blank=True, help_text='Operator-facing failure reason. Never returned as an answer.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_quality', models.FloatField(blank=True, help_text='0-1 confidence in the extracted text. Low values mark a document whose citations should be treated with caution rather than silently trusted.', null=True)),
                ('is_superseded', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('clause', 'Clause'), ('heading', 'Heading'), ('paragraph', 'Paragraph'), ('table', 'Table'), ('list', 'List'), ('footnote', 'Footnote'), ('preamble', 'Preamble')], max_length=16)),
                ('clause_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('depth', models.PositiveSmallIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField()),
                ('start_offset', models.PositiveIntegerField(default=0)),
                ('end_offset', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('detection_confidence', models.FloatField(default=1.0, help_text='Confidence from clause detection. Surfaced so a user can see which structure was inferred rather than certain.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentsection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_document_section',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('rotation', models.IntegerField(default=0)),
                ('extraction_method', models.CharField(choices=[('digital', 'Digital text extraction'), ('ocr', 'OCR'), ('hybrid', 'Hybrid (digital + OCR)'), ('none', 'No text extracted')], default='digital', max_length=16)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('has_tables', models.BooleanField(default=False)),
                ('has_images', models.BooleanField(default=False)),
                ('is_content_page', models.BooleanField(db_index=True, default=True, help_text='False for contents pages, indexes and front matter. Excluded from chunking — this flag is what prevents the contamination that required a manual purge in the legacy knowledge base.')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_document_page',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding_text', models.TextField(blank=True, help_text='Text actually embedded: the chunk prefixed with its clause context.')),
                ('clause_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('clause_title', models.CharField(blank=True, max_length=512)),
                ('heading_path', models.JSONField(blank=True, default=list)),
                ('start_page', models.PositiveIntegerField(db_index=True)),
                ('end_page', models.PositiveIntegerField()),
                ('start_offset', models.PositiveIntegerField(default=0)),
                ('end_offset', models.PositiveIntegerField(default=0)),
                ('is_complete_clause', models.BooleanField(default=False)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, help_text='Model that produced the embedding. Recorded so vectors from different models are never compared, and so a model change can be detected and the affected chunks re-embedded.', max_length=128)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='documents.documentsection')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_document_chunk',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='documents.documentversion'),
        ),
        migrations.AddIndex(
            model_name='documentcollection',
            index=models.Index(fields=['project', 'name'], name='documents_c_project_93b37d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='documents_d_documen_3e0c52_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['processing_status', 'created_at'], name='documents_d_process_ee570e_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version'),
        ),
        migrations.AddIndex(
            model_name='documentsection',
            index=models.Index(fields=['version', 'sequence'], name='documents_d_version_6f8533_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsection',
            index=models.Index(fields=['version', 'clause_number'], name='documents_d_version_220740_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsection',
            index=models.Index(fields=['parent'], name='documents_d_parent__d859c3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['version', 'page_number'], name='documents_d_version_0434bd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='doc_page_search_gin'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('version', 'page_number'), name='uniq_version_page'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['version', 'sequence'], name='documents_d_version_eb3a33_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['version', 'clause_number'], name='documents_d_version_f9c4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='doc_chunk_search_gin'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='doc_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('version', 'sequence'), name='uniq_version_chunk'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'document_type'], name='documents_d_project_4f1b21_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', '-document_date'], name='documents_d_project_6a326c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', '-created_at'], name='documents_d_project_e576e0_idx'),
        ),
    ]
