# Generated by Django 5.2.17 on 2026-09-15 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Set for reference documents, which have no project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Owning project. Null only for organization-level reference documents — the sources of knowledge bases — which never enter project retrieval or project document lists.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('project__isnull', False)), models.Q(('organization__isnull', False), ('project__isnull', True)), _connector='OR'), name='document_has_exactly_one_owner'),
        ),
    ]
