# Generated by Django 5.2.17 on 2026-09-15 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('edition_code', models.CharField(max_length=64)),
                ('llm_model', models.CharField(blank=True, max_length=128)),
                ('embedding_model', models.CharField(blank=True, max_length=128)),
                ('claim_snapshot', models.JSONField(default=dict, help_text='The claim as recorded when the run started. The analysis is of these facts, not of whatever the claim says today.')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True, help_text='Operator-facing. Never shown as, or mistaken for, an analysis finding.')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_claim_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisStrandResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strand', models.CharField(choices=[('evidence_gaps', 'Evidence gaps'), ('notice_compliance', 'Notice compliance'), ('entitlement', 'Contractual entitlement'), ('causation', 'Causation'), ('time_impact', 'Time impact'), ('quantum', 'Quantum'), ('counterarguments', 'Counterarguments')], max_length=32)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('uses_model', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('insufficient_evidence', models.BooleanField(default=False)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8)),
                ('confidence_reasons', models.JSONField(blank=True, default=list, help_text='Why the confidence is what it is. Computed, not self-reported.')),
                ('computed', models.JSONField(blank=True, default=dict, help_text='Deterministic output for computed strands — notice timing, the evidence gap report. Kept even when the model step fails.')),
                ('prompt_identifier', models.CharField(blank=True, max_length=128)),
                ('retrieval_query', models.TextField(blank=True)),
                ('observability', models.JSONField(blank=True, default=dict, help_text='Model, prompt version, retrieval trace, sources, citations and grounding outcome. No chain-of-thought is stored.')),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='analysis.claimanalysis')),
            ],
            options={
                'db_table': 'analysis_strand_result',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('statement', models.TextField()),
                ('epistemic_status', models.CharField(choices=[('fact', 'Fact'), ('inference', 'Inference'), ('opinion', 'Opinion'), ('unknown', 'Unknown')], max_length=16)),
                ('citations', models.JSONField(blank=True, default=list, help_text='Resolved citations: source ref, quotation, and the document, page, clause and edition each resolves to.')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_findings', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('strand_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='analysis.analysisstrandresult')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='analysis.claimanalysis')),
            ],
            options={
                'db_table': 'analysis_ai_finding',
                'ordering': ['strand_result__sequence', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='FindingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('amend', 'Amend')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('amended_statement', models.TextField(blank=True)),
                ('reviewer_email', models.EmailField(help_text='Recorded at review time. The review keeps its author even if the account is later removed.', max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='analysis.aifinding')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_finding_review',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='claimanalysis',
            index=models.Index(fields=['claim', '-created_at'], name='analysis_cl_claim_i_131a63_idx'),
        ),
        migrations.AddIndex(
            model_name='claimanalysis',
            index=models.Index(fields=['project', 'status'], name='analysis_cl_project_aa6f3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='claimanalysis',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('claim',), name='uniq_active_analysis_per_claim'),
        ),
        migrations.AddConstraint(
            model_name='analysisstrandresult',
            constraint=models.UniqueConstraint(fields=('analysis', 'strand'), name='uniq_strand_per_analysis'),
        ),
        migrations.AddIndex(
            model_name='aifinding',
            index=models.Index(fields=['claim', 'epistemic_status'], name='analysis_ai_claim_i_496e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='aifinding',
            index=models.Index(fields=['analysis', 'sequence'], name='analysis_ai_analysi_f5b5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='findingreview',
            index=models.Index(fields=['finding', 'created_at'], name='analysis_fi_finding_1a93a4_idx'),
        ),
    ]
