# Generated by Django 5.2.17 on 2026-09-12 22:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('edition_code', models.CharField(db_index=True, help_text="Edition code from the registry, e.g. 'red-book-2017'.", max_length=64)),
                ('form_code', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('published', 'Published'), ('quarantined', 'Quarantined')], db_index=True, default='draft', max_length=16)),
                ('source_filename', models.CharField(blank=True, max_length=512)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_report', models.JSONField(blank=True, default=dict, help_text='Latest ValidationReport. Blocking findings prevent publication.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='accounts.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_knowledge_base',
                'ordering': ['edition_code'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition_code', models.CharField(db_index=True, max_length=64)),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding_text', models.TextField(blank=True)),
                ('clause_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('clause_title', models.CharField(blank=True, max_length=512)),
                ('heading_path', models.JSONField(blank=True, default=list)),
                ('page_number', models.PositiveIntegerField()),
                ('is_complete_clause', models.BooleanField(default=False)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=128)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('is_quarantined', models.BooleanField(db_index=True, default=False, help_text='Excluded from retrieval by knowledge-base validation — contents pages, guidance notes, front matter. Retained rather than deleted so a validation rule can be revised without re-ingesting.')),
                ('quarantine_reason', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgebase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_knowledge_base_chunk',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['organization', 'status'], name='knowledge_k_organiz_28d78d_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'edition_code'), name='uniq_kb_edition_per_org'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasechunk',
            index=models.Index(fields=['knowledge_base', 'sequence'], name='knowledge_k_knowled_b098ac_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasechunk',
            index=models.Index(fields=['edition_code', 'clause_number'], name='knowledge_k_edition_cd33bc_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasechunk',
            index=models.Index(fields=['edition_code', 'is_quarantined'], name='knowledge_k_edition_605328_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='kb_chunk_search_gin'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='kb_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasechunk',
            constraint=models.UniqueConstraint(fields=('knowledge_base', 'sequence'), name='uniq_kb_chunk_sequence'),
        ),
    ]
