# Generated by Django 5.2.17 on 2026-09-15 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_organization_alter_document_project_and_more'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='build_error',
            field=models.TextField(blank=True, help_text='Why the last build failed. Operator-facing.'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='The organization-level reference document the edition was built from. It runs through the same ingestion pipeline as project documents but has no project, so it never appears in project retrieval (docs/PHASE7.md, D2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing source'), ('failed', 'Processing failed'), ('validating', 'Validating'), ('ready', 'Ready to publish'), ('published', 'Published'), ('quarantined', 'Quarantined')], db_index=True, default='draft', max_length=16),
        ),
    ]
