# Generated by Django 5.2.17 on 2026-09-13 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('subject', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('letter', 'Letter'), ('email', 'Email'), ('notice', 'Notice'), ('instruction', "Engineer's Instruction"), ('determination', 'Determination'), ('response', 'Response'), ('minutes', 'Meeting minutes'), ('rfi', 'Request for Information'), ('site_instruction', 'Site instruction'), ('other', 'Other')], db_index=True, default='letter', max_length=32)),
                ('direction', models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], max_length=16)),
                ('sender_raw', models.CharField(blank=True, help_text='Sender exactly as written on the document. Retained alongside the resolved Party so an attribution can be checked, and so a wrong match is correctable rather than invisible.', max_length=255)),
                ('recipient_raw', models.CharField(blank=True, max_length=255)),
                ('sent_date', models.DateField(blank=True, db_index=True, null=True)),
                ('received_date', models.DateField(blank=True, help_text='Most notice provisions turn on receipt, so this is preferred over sent_date when computing compliance.', null=True)),
                ('clause_references', models.JSONField(blank=True, default=list)),
                ('is_ai_extracted', models.BooleanField(default=False)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='documents.document')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='correspondence.correspondence')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='projects.project')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_correspondence', to='projects.party')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_correspondence', to='projects.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'correspondence',
                'db_table': 'correspondence_correspondence',
                'ordering': ['-sent_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_number', models.CharField(help_text='The provision the Notice is given under, e.g. 20.2.1.', max_length=32)),
                ('edition_code', models.CharField(blank=True, help_text='Governing edition. Recorded because notice periods and their consequences differ between editions (ADR 0004).', max_length=64)),
                ('is_confirmed_notice', models.BooleanField(default=False, help_text='A human has confirmed this satisfies the provision. Until then the compliance finding carries a caveat rather than treating it as one.')),
                ('notes', models.TextField(blank=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='claims.claim')),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='correspondence.correspondence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'correspondence_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['project', '-sent_date'], name='corresponde_project_c9081c_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['project', 'kind'], name='corresponde_project_15ddc9_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['sender', '-sent_date'], name='corresponde_sender__2b78d6_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['project', 'clause_number'], name='corresponde_project_f21f15_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['claim'], name='corresponde_claim_i_f18310_idx'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('correspondence', 'clause_number'), name='uniq_notice_per_clause'),
        ),
    ]
