# Generated by Django 5.2.17 on 2026-10-07 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_contract_deadlines'),
        ('correspondence', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notice',
            name='uniq_notice_per_clause',
        ),
        migrations.AddField(
            model_name='notice',
            name='obligation',
            field=models.CharField(blank=True, choices=[('notice_of_claim', 'Notice of claim'), ('detailed_claim', 'Detailed claim / particulars')], help_text='Whether this is the notice or the detailed submission that follows it. One clause can impose both (FIDIC 1987 Sub-Clause 44.2, 1999 Sub-Clause 20.1), so the clause alone cannot say. Blank means not recorded, and the item counts towards either.', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('correspondence', 'clause_number', 'obligation'), name='uniq_notice_per_clause_obligation'),
        ),
    ]
